import type { NextPage } from 'next';
import { useState } from 'react';
import axios from 'axios';
import Head from 'next/head';
import styled from 'styled-components';
import { ICharacter } from '../interfaces';
import { Character } from '../components';

interface CharactersProps {
  characters: ICharacter[];
}

const Characters: NextPage<CharactersProps> = ({ characters }) => {
  const [value, setValue] = useState(12);
  const handleShowMore = () => setValue(value + 12);
  return (
    <>
      <Head>
        <title>Star Wars Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScreenContainer>
        <StarfieldLeft />
        <CharactersContainer>
          {characters
            .filter((c) => c.id !== 22 && c.id !== 77)
            .map(
              (c, index) =>
                index < value && <Character key={c.id} character={c} />
            )}
        </CharactersContainer>
        {value < characters.length && (
          <Button onClick={handleShowMore}>SHOW MORE</Button>
        )}
        <StarfieldRight />
      </HomeScreenContainer>
    </>
  );
};

export const getStaticProps = async () => {
  const { data: characters } = await axios.get(
    'https://akabab.github.io/starwars-api/api/all.json'
  );
  return {
    props: {
      characters,
    },
  };
};

const HomeScreenContainer = styled.div``;

const Starfield = styled.div`
  position: fixed;
  width: 200px;
  height: 1700px;
  top: 0;
  background-repeat: repeat-y;
`;

export const StarfieldLeft = styled(Starfield)`
  left: 0;
  background-position: left center;
  background-size: 100% auto;
  background-image: url('https://static-mh.content.disney.io/starwars/assets/background/bg_starsL-fd4661a3ccea.jpg');
`;

export const StarfieldRight = styled(Starfield)`
  right: 0;
  background-position: right center;
  background-size: auto 100%;
  background-image: url('https://static-mh.content.disney.io/starwars/assets/background/bg_starsR-655c85e404d4.jpg');
`;

const CharactersContainer = styled.div`
  display: flex;
  margin-top: 200px;
  flex-wrap: wrap;
  gap: 1.5625rem;
  justify-content: center;
  padding: 1.875rem;
  background-color: #151515;
`;

const Button = styled.button`
  color: #aaa;
  background-color: transparent;
  border: none;
  font-family: inherit;
  margin: 1.25rem auto 1.25rem auto;
  font-size: 1.125rem;
  display: block;
  transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);

  :hover {
    cursor: pointer;
    color: #fff;
  }

  :hover::after {
    border-bottom-color: #fff;
    width: 100%;
  }

  ::after {
    content: '';
    display: block;
    width: 40%;
    margin: 0 auto;
    opacity: 0.9;
    border-bottom: 1px solid transparent;
    transition: border-color 200ms, width 250ms;
  }
`;

export default Characters;
